"""prevent duplicate source files

Revision ID: 2a9c6ddc863b
Revises: 9a98cca6de48
Create Date: 2026-08-05 18:00:28.051493

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a9c6ddc863b'
down_revision: str | Sequence[str] | None = '9a98cca6de48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_source_file_checksum', 'documents', ['source', 'file_checksum'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_source_file_checksum', 'documents', type_='unique')
    # ### end Alembic commands ###
