"""add provider aware document analyses

Revision ID: 4a6ef28aa57a
Revises: f047557ca1c7
Create Date: 2026-08-12 10:38:58.456915

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a6ef28aa57a'
down_revision: str | Sequence[str] | None = 'f047557ca1c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('primary_category', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=250), nullable=False),
    sa.Column('relevance_explanation', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_id', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_provider'), 'document_analyses', ['provider'], unique=False)
    op.add_column('relevance_assessments', sa.Column('provider', sa.String(length=30), server_default='openai', nullable=False))
    op.add_column('relevance_assessments', sa.Column('model', sa.String(length=120), nullable=True))
    op.add_column('relevance_assessments', sa.Column('prompt_version', sa.String(length=50), server_default='legacy', nullable=False))
    op.add_column('relevance_assessments', sa.Column('response_id', sa.String(length=255), nullable=True))
    op.add_column('relevance_assessments', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('relevance_assessments', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relevance_assessments', 'output_tokens')
    op.drop_column('relevance_assessments', 'input_tokens')
    op.drop_column('relevance_assessments', 'response_id')
    op.drop_column('relevance_assessments', 'prompt_version')
    op.drop_column('relevance_assessments', 'model')
    op.drop_column('relevance_assessments', 'provider')
    op.drop_index(op.f('ix_document_analyses_provider'), table_name='document_analyses')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
