"""create initial document schema

Revision ID: 9a98cca6de48
Revises: 
Create Date: 2026-08-05 17:34:52.381161

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a98cca6de48'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('DUPO', 'TCP', name='source_enum', native_enum=False), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=512), nullable=True),
    sa.Column('file_checksum', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_date', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('units_processed', sa.Integer(), nullable=False),
    sa.Column('text_complete', sa.Boolean(), nullable=False),
    sa.Column('text_method', sa.String(length=50), nullable=True),
    sa.Column('relevance_status', sa.Enum('not_assessed', 'uncertain', 'relevant', 'irrelevant', 'needs_manual_review', name='relevance_status_enum', native_enum=False), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_confidence', sa.Float(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('classification_status', sa.Enum('not_classified', 'partial_text', 'full_text', name='classification_status_enum', native_enum=False), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', name='uq_documents_source_record_id')
    )
    op.create_index(op.f('ix_documents_file_checksum'), 'documents', ['file_checksum'], unique=False)
    op.create_index(op.f('ix_documents_language'), 'documents', ['language'], unique=False)
    op.create_index(op.f('ix_documents_primary_category'), 'documents', ['primary_category'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index('ix_documents_relevance_category', 'documents', ['relevance_status', 'primary_category'], unique=False)
    op.create_index(op.f('ix_documents_relevance_status'), 'documents', ['relevance_status'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index('ix_documents_source_year', 'documents', ['source', 'year'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('document_text_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('processing_method', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'unit_type', 'unit_number', name='uq_document_text_unit')
    )
    op.create_index(op.f('ix_document_text_units_document_id'), 'document_text_units', ['document_id'], unique=False)
    op.create_table('dupo_metadata',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('dupo_id', sa.String(length=255), nullable=True),
    sa.Column('knuttel_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_dupo_metadata_dupo_id'), 'dupo_metadata', ['dupo_id'], unique=True)
    op.create_index(op.f('ix_dupo_metadata_knuttel_number'), 'dupo_metadata', ['knuttel_number'], unique=False)
    op.create_table('relevance_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('units_processed', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('not_assessed', 'uncertain', 'relevant', 'irrelevant', 'needs_manual_review', name='assessment_decision_enum', native_enum=False), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('primary_category', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('classification_status', sa.Enum('not_classified', 'partial_text', 'full_text', name='assessment_classification_status_enum', native_enum=False), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sequence_number', name='uq_relevance_assessment_sequence')
    )
    op.create_index(op.f('ix_relevance_assessments_document_id'), 'relevance_assessments', ['document_id'], unique=False)
    op.create_table('tcp_metadata',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tcp_id', sa.String(length=255), nullable=True),
    sa.Column('eebo_id', sa.String(length=255), nullable=True),
    sa.Column('vid', sa.String(length=255), nullable=True),
    sa.Column('stc', sa.String(length=255), nullable=True),
    sa.Column('source_status', sa.String(length=255), nullable=True),
    sa.Column('source_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_pages', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_tcp_metadata_eebo_id'), 'tcp_metadata', ['eebo_id'], unique=False)
    op.create_index(op.f('ix_tcp_metadata_stc'), 'tcp_metadata', ['stc'], unique=False)
    op.create_index(op.f('ix_tcp_metadata_tcp_id'), 'tcp_metadata', ['tcp_id'], unique=True)
    op.create_index(op.f('ix_tcp_metadata_vid'), 'tcp_metadata', ['vid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tcp_metadata_vid'), table_name='tcp_metadata')
    op.drop_index(op.f('ix_tcp_metadata_tcp_id'), table_name='tcp_metadata')
    op.drop_index(op.f('ix_tcp_metadata_stc'), table_name='tcp_metadata')
    op.drop_index(op.f('ix_tcp_metadata_eebo_id'), table_name='tcp_metadata')
    op.drop_table('tcp_metadata')
    op.drop_index(op.f('ix_relevance_assessments_document_id'), table_name='relevance_assessments')
    op.drop_table('relevance_assessments')
    op.drop_index(op.f('ix_dupo_metadata_knuttel_number'), table_name='dupo_metadata')
    op.drop_index(op.f('ix_dupo_metadata_dupo_id'), table_name='dupo_metadata')
    op.drop_table('dupo_metadata')
    op.drop_index(op.f('ix_document_text_units_document_id'), table_name='document_text_units')
    op.drop_table('document_text_units')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index('ix_documents_source_year', table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_relevance_status'), table_name='documents')
    op.drop_index('ix_documents_relevance_category', table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_primary_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_language'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_checksum'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
