"""add document provider states

Revision ID: bf3638aee820
Revises: 9cb04eaae4a0
Create Date: 2026-08-12 14:13:09.519579

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf3638aee820'
down_revision: str | Sequence[str] | None = '9cb04eaae4a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_provider_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('relevance_status', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=250), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('last_assessment_number', sa.Integer(), nullable=False),
    sa.Column('units_processed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'provider', name='uq_document_provider_state')
    )
    op.create_index(op.f('ix_document_provider_states_document_id'), 'document_provider_states', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_provider_states_provider'), 'document_provider_states', ['provider'], unique=False)
    op.drop_constraint(op.f('relevance_assessments_document_id_provider_sequence_number_key'), 'relevance_assessments', type_='unique')
    op.create_unique_constraint('uq_relevance_document_provider_sequence', 'relevance_assessments', ['document_id', 'provider', 'sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_relevance_document_provider_sequence', 'relevance_assessments', type_='unique')
    op.create_unique_constraint(op.f('relevance_assessments_document_id_provider_sequence_number_key'), 'relevance_assessments', ['document_id', 'provider', 'sequence_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_document_provider_states_provider'), table_name='document_provider_states')
    op.drop_index(op.f('ix_document_provider_states_document_id'), table_name='document_provider_states')
    op.drop_table('document_provider_states')
    # ### end Alembic commands ###
