"""store OCR provenance on text units

Revision ID: f047557ca1c7
Revises: 2a9c6ddc863b
Create Date: 2026-08-06 11:39:36.129422

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f047557ca1c7'
down_revision: str | Sequence[str] | None = '2a9c6ddc863b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_text_units', sa.Column('ocr_provider', sa.String(length=50), nullable=True))
    op.add_column('document_text_units', sa.Column('ocr_model', sa.String(length=200), nullable=True))
    op.add_column('document_text_units', sa.Column('provider_response_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_text_units', 'provider_response_id')
    op.drop_column('document_text_units', 'ocr_model')
    op.drop_column('document_text_units', 'ocr_provider')
    # ### end Alembic commands ###
